### ISSUE TITLE
Je pense qu'il serait souhaitable de justifier les textes libres de chaque page (svp)

### ISSUE THREAD

**Issue by Tdelcey** [SuperMayo/rehpere#1]
Certains pages ont des textes libres normés d'autres non.

**Comment by SuperMayo** [comment]
Merci de préciser les pages concernées.

**Comment by Tdelcey** [comment]
Il s'agit de toute les pages de présentation des différents enseignements. Si la justification est liée  a une commande je veux bien l'apprendre :)

**Comment by gnoblet** [comment]
La page "Actualités" est aussi non-justifiée (lié au markdown ?)
