### ISSUE TITLE
author-id can only refer to one member

### ISSUE THREAD

**Issue by gnoblet** [SuperMayo/rehpere#18]
If two or more members have written an article, only one can be referred to with the "authorid" field in the .bib file.

Is it possible to transform it so that multiple members' authorid are taken into account?

**Comment by Tdelcey** [comment]
Any news about this issue? I am actually updating the publications of the members and there is a lot of co-authoring. Thus, in the personal pages of co-authors, these publications do not appear.

**Comment by SuperMayo** [comment]
I think I know how to solve this issue. Will try to solve it this week.

Just for me I add these references:
> - The authorid field in the bibliography will need to have all author IDs separated with blank space (or comma)
> - Instead of matching the authorid with `--query @*[authorid={{page.flatname}}`, I can use `--query @*[authorid ~={{page.flatname}}` (See [doc here](https://github.com/inukshuk/bibtex-ruby#queries))
