### ISSUE TITLE
Font size of posts' title is too big

### ISSUE THREAD

**Issue by gnoblet** [SuperMayo/rehpere#24]
The font size of posts' title is too big.

I think we could go for the same font size as for "Latest publications" under "Publications".

**Comment by SuperMayo** [comment]
Are you talking of the title font size for the list of publications (ie on [this page](https://rehpere.com/actualites/) ) or when you focus on a single post ( like  on [this page](https://rehpere.com/2018/11/15/cee-mongin-fr) )  ?
