### ISSUE TITLE
Design page publication, listage trop lourd visuellement. Serait il possible de faire quelque chose ? (svp)

### ISSUE THREAD

**Issue by Tdelcey** [SuperMayo/rehpere#3]
- page trop lourde, espacement. 
- rajout de date

**Comment by SuperMayo** [comment]
Que veux-tu dire par "rajout de date" ? Il y a déjà les dates des publications

**Comment by Tdelcey** [comment]
Pardon, c'est pas très clair. Dans la logique d'espacer le contenue de la page actuelle des publications, je pensais séparer les publications par leur année de publication. Ça donnerait quelque chose de la forme suivante: 

2018

Delcey Thomas, 2018, nom de l'article. 
Guillaume le Noble, 2018, nom de l'article. 
Delcey Thomas, 2018, nom de l'article. 

2017, 

Delcey Thomas, 2017, nom de l'article.
