### ISSUE TITLE
Remove members status on page "members"

### ISSUE THREAD

**Issue by gnoblet** [SuperMayo/rehpere#5]
Just use "alphabetic" listing of people for page "members" instead of "status".
Yet keep the status on personal pages.

**Comment by SuperMayo** [comment]
@gnoblet  Do you mean replacing the existing menu with an alphabetical menu ( I mean by that a simple nav menu with letters), or do you just mean removing the menu and ordering people by their last name ?

**Comment by gnoblet** [comment]
> @gnoblet Do you mean replacing the existing menu with an alphabetical menu ( I mean by that a simple nav menu with letters), or do you just mean removing the menu and ordering people by their last name ?

I meant ordering people by their last name
Yet if you think it is nicer and more useful with an alphabetical menu, and not hard to design, go ahead: I don't mind
