### ISSUE TITLE
- Pb de clic:

### ISSUE THREAD

**Issue by JustineGluglu** [SuperMayo/rehpere#7]
Page "Membres", lorsque l'on clique sur "professeur", etc., ça renvoie à la bonne hauteur de page correspondante. Mais cette fonctionnalité ne marche pas pour "Maître d'enseignement" et "Maître de conférence". D'ailleurs, il faudrait mettre toutes ces catégories au pluriel!

**Comment by SuperMayo** [comment]
Concerne maintenant une ancienne version du site ( cf #5 )
